# Generated by Django 3.1.6 on 2021-02-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField()),
                ('price', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=10)),
                ('company', models.CharField(choices=[('ALLEGRO', 'Allegro'), ('BONPRIX', 'bonprix'), ('ŻABKA', 'Żabka'), ('DECATHLON', 'decathlon'), ('SPOTIFY', 'spotify'), ('EOBUWIE', 'eobuwie'), ('SFD', 'sklep_sfd'), ('IKEA', 'ikea'), ('ZARA', 'zara')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
