# Generated by Django 3.1.6 on 2021-02-21 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=False)),
                ('points', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('place_of_residence', models.IntegerField(choices=[(1, 'Village'), (2, 'Town'), (3, 'City')], null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('fitness_level', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
