# Generated by Django 3.1.6 on 2021-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.ManyToManyField(to='polls.QuestionOption'),
        ),
    ]
