# Generated by Django 3.1.6 on 2021-02-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210221_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option',
            new_name='options',
        ),
    ]
