# Generated by Django 3.1.6 on 2021-02-24 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20210221_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollassignment',
            unique_together={('user', 'poll')},
        ),
    ]
