# Generated by Django 3.1.6 on 2021-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210224_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='answer',
            field=models.ManyToManyField(null=True, to='polls.Answer'),
        ),
    ]
