# Generated by Django 3.1.6 on 2021-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210225_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='answer',
            field=models.ManyToManyField(to='polls.Answer'),
        ),
    ]
