# Generated by Django 3.1.6 on 2021-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210225_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('SPORT', 'Sport'), ('POLITICS', 'Politics'), ('LIFE_STYLE', 'Life Style'), ('BUSINESS', 'Business')], max_length=100),
        ),
    ]
